### ISSUE TITLE
Normalize API to EventEmitter?

### ISSUE THREAD

**Issue by dhruvbird** [aaronpowell/Postman#1]
Hello,
  Was wondering why you didn't normalize the API to that of the EventEmitter() so that people can use it as a drop-in-replacement?

**Comment by aaronpowell** [comment]
The main reason is that Postman was originally written without Node.js support so hence EventEmitter isn't available. Ultimately I want Postman to be agnostic of Node.js vs in-browser JavaScript.

Also EventEmitter is more designed for connecting instances of a type to callbacks, rather than disconnected eventing that I've designed tihs around.

That said looking at this from the perspective of a Node developer it would make sense to have an API that resembles the EventEmitter, so I might look into whether I can augment the API exposed through Node to look like the EventEmitter (even if it's not used under the hood).
